// Bu dosya content.js içindeki kavramlar dizisine eklenecek 88 yeni kavramdır.
// Uygulama tarafında: C.kavramlar = C.kavramlar.concat(window.KAVRAMLAR_EK);

window.KAVRAMLAR_EK = [
  // ── MALZEME ──────────────────────────────────────────────────────────
  {id:"k13",kategori:"Malzeme",ad:"Kırılma tokluğu",en:"Fracture toughness",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Bir malzemenin içindeki çatlağın büyümesine karşı gösterdiği dirençtir. K_IC ile simgelenir, MPa√m birimiyle ölçülür. Yüksek kırılma tokluğu, malzemenin çatlak içerse bile kolayca kırılmayacağı anlamına gelir. Titanyum alaşımları hem yüksek dayanım hem iyi kırılma tokluğu sunar; bu yüzden uçak gövde bağlantı noktalarında tercih edilir.",
   soru:"Dayanımı yüksek olan malzeme neden kırılma tokluğu düşük olabilir?",
   cevap:"Sertleştirme işlemleri malzemeyi güçlü ama kırılgan yapar. Yüksek dayanımlı çelikler ve seramikler buna örnektir. Mühendislik tasarımında her ikisi de gözetilmeli, sadece birine odaklanılmamalıdır."},
  {id:"k14",kategori:"Malzeme",ad:"S-N eğrisi",en:"S-N curve (Wöhler curve)",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Bir malzemenin belirli bir gerilme genliğinde kaç çevrimde kırıldığını gösteren grafiktir. Yatay eksende çevrim sayısı (N), dikey eksende gerilme genliği (S) yer alır. Bazı çelikler belirli bir gerilmenin altında hiç yorulmaz; buna yorulma sınırı denir. Alüminyum ve titanyum alaşımlarında yorulma sınırı yoktur. Comet uçak kazaları S-N eğrisinin tasarımda neden kritik olduğunu göstermiştir.",
   soru:"Alüminyum alaşımlarında neden yorulma sınırı yoktur?",
   cevap:"Kristal yapı ve dislokasyon hareketleri nedeniyle alüminyumda yorulma hasarı birikimi durdurulamaz. Bu yüzden uçak gövdelerinde ömür sınırı belirlenir ve o süre dolmadan bileşen değiştirilir."},
  {id:"k15",kategori:"Malzeme",ad:"Sürünme",en:"Creep",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Malzemenin yüksek sıcaklıkta sabit yük altında zamanla yavaşça şekil değiştirmesidir. Türbin kanatçıkları çalışma sıcaklıklarında sürekli sürünme zorlamasına maruz kalır. Nikel süperalaşımları ve tek kristal kanat geometrileri sürünme direncini artırmak için geliştirilmiştir. Erime noktasının 0,3-0,4 katı sıcaklıktan itibaren sürünme önemli hale gelir.",
   soru:"Sürünme neden oda sıcaklığında önemli olmaz?",
   cevap:"Atomların difüzyon hızı sıcaklıkla üstel artar. Oda sıcaklığı çoğu metalin erime noktasının çok altındadır. Kurşun ve kalay gibi erime noktası düşük metaller ise oda sıcaklığında bile sürünebilir."},
  {id:"k16",kategori:"Malzeme",ad:"Korozyon",en:"Corrosion",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Metalin çevreyle kimyasal veya elektrokimyasal tepkimeye girerek bozunmasıdır. Galvanik korozyon iki farklı metalin elektrolitli ortamda teması sonucu oluşur. Kompozit-alüminyum arayüzleri galvanik korozyon açısından dikkatli tasarım gerektirir. Çukur korozyon, gerilme korozyon çatlaması ve aralık korozyonu havacılıkta en sık karşılaşılan türlerdir.",
   soru:"Karbon fiber kompozit ile alüminyum neden doğrudan temas ettirilmez?",
   cevap:"Karbon fiber iletkendir ve alüminyumla galvanik çift oluşturur. Alüminyum bu çiftte anot konumuna düşer ve hızla korozyona uğrar. Aralarına cam elyaf tabakası veya teflon bant konularak bu temas engellenir."},
  {id:"k17",kategori:"Malzeme",ad:"Isıl işlem",en:"Heat treatment",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Malzemenin mekanik özelliklerini değiştirmek için kontrollü ısıtma ve soğutma işlemidir. Tavlama malzemeyi yumuşatır, su verme sertleştirir, menevişleme kırılganlığı azaltır. Alüminyum alaşımlarında yaşlandırma işlemi çökelme sertleşmesiyle mukavemeti artırır. 7075-T6 alüminyumundaki T6 çözelti ısıl işlemi ve yapay yaşlandırma uygulandığını gösterir.",
   soru:"Su verme sonrası neden menevişleme yapılır?",
   cevap:"Su verme malzemeyi çok sert ama kırılgan yapar. Martensit yapısında büyük iç gerilmeler oluşur. Menevişleme bu gerilmeleri azaltır ve tokluk kazandırır."},
  {id:"k18",kategori:"Malzeme",ad:"Özgül dayanım ve özgül rijitlik",en:"Specific strength and stiffness",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Özgül dayanım, malzemenin çekme dayanımının yoğunluğuna oranıdır. Özgül rijitlik ise elastisite modülünün yoğunluğa oranıdır. Hafiflik gerektiren havacılık yapılarında bu iki değer Ashby diyagramıyla karşılaştırılır. Karbon elyaf-epoksi kompozitleri hem özgül dayanımda hem özgül rijitlikte metalleri geride bırakır.",
   soru:"Karbon fiber çelikten daha mı güçlüdür?",
   cevap:"Mutlak değerlerde değil ama özgül dayanımda evet. Çeliğin çekme dayanımı daha yüksek olabilir; ama çelik çok daha ağırdır. Aynı ağırlık için karbon fiber çok daha fazla yük taşır."},
  {id:"k19",kategori:"Malzeme",ad:"Dislokasyon ve pekiştirme",en:"Dislocation and strengthening",mulakat:false,branslar:["ucak","uzay"],
   tanim:"Dislokasyon, kristal kafeste bir sıra atomun yarım kaldığı çizgisel bir kusurdur. Malzeme plastik şekil değiştirirken dislokasyonlar hareket eder. Dislokasyon hareketini engellemek malzemeyi pekiştirir. Soğuk şekillendirme, alaşımlama, çökelme ve tane sınırı pekiştirme başlıca yöntemlerdir.",
   soru:"Soğuk şekillendirme malzemeyi neden pekiştirir?",
   cevap:"Plastik deformasyon sırasında dislokasyon yoğunluğu artar. Dislokasyonlar birbirini engellemeye başlar ve hareket edemez hale gelir. Hareket edemeyen dislokasyon plastik deformasyon olamaz, yani malzeme sertleşmiş demektir."},
  {id:"k20",kategori:"Malzeme",ad:"Tane yapısı ve Hall-Petch",en:"Grain structure",mulakat:false,branslar:["ucak","uzay"],
   tanim:"Metaller polikristal yapıdadır. Her tane farklı kristal yöneliminde küçük bir kristaldir. Hall-Petch ilişkisine göre tane boyutu küçüldükçe akma dayanımı artar. İnce taneli çelikler hem daha sağlam hem de daha toktur; iri taneli çelikler daha kırılgan davranır.",
   soru:"Tane boyutunu küçültmenin pratik sınırı var mıdır?",
   cevap:"Evet. Nano-kristal malzemelerde tane sınırı yüzdesi çok artar ve mekanizma değişir. Üretim güçleşir ve bazı özellikler tersine dönebilir. İnce taneli malzemeler yüksek sıcaklıkta tane büyümesine karşı da hassastır."},
  {id:"k21",kategori:"Malzeme",ad:"Faz diyagramı",en:"Phase diagram",mulakat:false,branslar:["ucak","uzay"],
   tanim:"Bir malzeme sisteminde sıcaklık ve bileşime göre hangi fazların kararlı olduğunu gösteren haritadır. Demir-karbon diyagramı mühendislik metalurjisinin temelidir. Liquidus ve solidus çizgileri, ötektik ve peritekik noktalar kritik kavramlardır. Isıl işlemin etkisini anlamak için faz diyagramı şarttır.",
   soru:"Çeliğin dökme demirden farkı nedir, faz diyagramı açısından?",
   cevap:"Çelikte karbon oranı yüzde 0,02-2,14 arasındadır ve işlenebilirdir. Dökme demirde karbon yüzde 2,14 ün üstüne çıkar, grafitik veya karbürlü yapı oluşur, dövülemez ama dökülebilir."},
  {id:"k22",kategori:"Malzeme",ad:"Ablatif malzeme",en:"Ablative material",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Atmosfere giriş veya roket motor lülesinde aşırı ısıya maruz kalan yüzeyleri korumak için kullanılan malzemelerdir. Isı enerjisini malzemenin buharlaşması, erimesi ve yanmasıyla uzaklaştırır. Apollo kapsülünde ablasyon tabakası kullanılmıştır. SpaceX Dragon kapsülü PICA-X malzemesi kullanır.",
   soru:"Ablasyon ile ısıl bariyer kaplama arasındaki fark nedir?",
   cevap:"Ablasyon tek kullanımlıktır, malzeme buharlaşarak ısıyı götürür. Isıl bariyer kaplama türbin kanatlarında kullanılır, yerinde kalır ve sadece ısıyı iletmez. Ablasyon çok daha yüksek ısı akısını kısa süre taşıyabilir."},

  // ── ANALİZ ───────────────────────────────────────────────────────────
  {id:"k23",kategori:"Analiz",ad:"Gerilme konsantrasyonu",en:"Stress concentration",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Kesit alanının aniden değiştiği yerlerde, deliklerde, çentiklerde ve köşelerde gerilmenin ortalamanın çok üstüne çıkmasıdır. Kt katsayısıyla ifade edilir. Oval pencereler yerine köşeli pencere kullanan Comet uçaklarının köşe çatlaklarından yıkılması bu kavramın en çarpıcı örneğidir. İyi tasarım keskin köşelerden kaçınır, geçişleri yumuşatır.",
   soru:"Köşeli yerine oval pencere kullanmak neden önemlidir?",
   cevap:"Keskin köşe Kt değerini çok yükseltir. Uçak gövdesi basınçlandırma çevrimlerinde yorulma yükleri taşır. Yüksek gerilme konsantrasyonu bu noktada çatlak başlatır ve yorulma ömrünü dramatik biçimde düşürür. Yuvarlatılmış köşeler gerilmeyi yayar."},
  {id:"k24",kategori:"Analiz",ad:"Mohr dairesi",en:"Mohr circle",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Bir noktadaki gerilme durumunu farklı düzlemlerde görsel olarak gösteren grafik yöntemidir. Dairenin merkezi ortalama normal gerilmeyi, yarıçapı ise maksimum kayma gerilmesini verir. Asal gerilmeler dairenin yatay eksenle kesiştiği noktalardır. Mülakatlarda elle çizmek istenebilir; mantığını bilmek ezberden önemlidir.",
   soru:"Asal gerilme düzleminde kayma gerilmesi neden sıfırdır?",
   cevap:"Asal gerilme düzlemi, normal gerilmenin maksimum veya minimum olduğu düzlemdir. Mohr dairesinde bu noktalar kayma gerilmesinin sıfır olduğu noktalardır. Matematiksel olarak türevin sıfır olduğu yer, fiziksel olarak yük doğrultusuyla hizalı düzlemdir."},
  {id:"k25",kategori:"Analiz",ad:"Burkulma",en:"Buckling",mulakat:true,branslar:["ucak","uzay"],
   tanim:"İnce bir elemanın eksenel basınç altında aniden yanal yönde eğilmesidir. Euler burkulma yükü P_cr = π²EI/L² formülüyle hesaplanır. Yük, malzemenin akma dayanımına ulaşmadan bile burkulma gerçekleşebilir. Uçak kaplamaları ve uzay aracı güneş paneli destekleri burkulmaya karşı tasarlanmalıdır.",
   soru:"Euler formülü hangi durumda geçersiz kalır?",
   cevap:"Burkulma gerilmesi malzemenin orantı sınırını aşarsa Euler formülü geçersizdir. Kısa ve kalın sütunlar için Johnson veya Rankine formülleri kullanılır."},
  {id:"k26",kategori:"Analiz",ad:"Yorulma çatlağı büyümesi",en:"Fatigue crack growth",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Tekrarlı yükler altında bir çatlağın her çevrimde küçük miktarda büyümesidir. Paris yasası da/dN = C(ΔK)^m ile tanımlanır. Havacılıkta hasar toleranslı tasarım yaklaşımı bu ilkeye dayanır: çatlak kritik boyuta ulaşmadan muayeneyle tespit edilmeli ve parça değiştirilmelidir.",
   soru:"Güvenli ömür ve hasar toleransı tasarımı arasındaki fark nedir?",
   cevap:"Güvenli ömür tasarımında yapı hiç çatlak olmayacak şekilde ömürlendirilir. Hasar toleransı tasarımında çatlak oluşabilir kabul edilir ama kritik boyuta ulaşmadan muayeneyle yakalanır. Modern sivil havacılık hasar toleransı yaklaşımını benimser."},
  {id:"k27",kategori:"Analiz",ad:"Titreşim ve rezonans",en:"Vibration and resonance",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Doğal frekans, bir sistemin serbest titreşim frekansıdır. Dışarıdan gelen zorlamanın frekansı doğal frekansa eşlenirse rezonans oluşur ve genlik büyür. Uçak kanatları, motor ve gövde arasındaki titreşim etkileşimi kritik tasarım konularıdır.",
   soru:"Bir yapının doğal frekansını nasıl değiştirirsin?",
   cevap:"Kütle artarsa frekans düşer, rijitlik artarsa frekans yükselir. f = √(k/m) formülü bu ilişkiyi özetler. Pratik yöntemler: kütle eklemek, sönümleme elemanı koymak, rijitliği veya geometriyi değiştirmek."},
  {id:"k28",kategori:"Analiz",ad:"FEA: mesh kalitesi",en:"FEA mesh quality",mulakat:true,branslar:["ucak","uzay"],
   tanim:"FEA sonucunun doğruluğu büyük ölçüde mesh kalitesine bağlıdır. Eleman şekli bozuldukça hata artar. Yüksek gerilme gradyanı olan bölgelerde mesh sıkılaştırılmalıdır. Mesh yakınsama analizi: elemanlar küçüldükçe sonuç değişmiyorsa mesh yeterlidir. Keskin köşelerde geometrik tekillik oluşur; bu noktalara körü körüne güvenilmemelidir.",
   soru:"Mesh yakınsama analizini nasıl yaparsın?",
   cevap:"Kaba bir meshle başlarsın, kritik bölgedeki sonucu kaydedersin. Mesh sıkılaştırır, sonucu tekrar alırsın. İki sonuç arasındaki fark küçükse yakınsama sağlanmıştır. Genelde yüzde 5 in altındaki değişim kabul edilebilir sayılır."},
  {id:"k29",kategori:"Analiz",ad:"CFD: sınır koşulları",en:"CFD boundary conditions",mulakat:true,branslar:["ucak","uzay"],
   tanim:"CFD analizinde sınır koşulları sonucu doğrudan belirler. Giriş: hız veya basınç profili. Çıkış: basınç değeri. Duvar: kayma olmayan koşul (no-slip). Yanlış sınır koşulu doğru mesh ve türbülans modelinden daha fazla hataya yol açar.",
   soru:"Rüzgâr tüneli testini CFD ile doğrulamak istiyorsun. Hangi sınır koşulunu dikkatli seçmelisin?",
   cevap:"Tünel duvarlarını modellemek kritiktir. Sonsuz serbest akış varsayılırsa tünel duvarlarının blokaj etkisi atlanır. Blokaj oranı yüksekse sonuçlar arasında ciddi fark çıkar."},
  {id:"k30",kategori:"Analiz",ad:"Aeroelastisite",en:"Aeroelasticity",mulakat:true,branslar:["ucak"],
   tanim:"Aerodinamik kuvvetler, yapısal elastisite ve atalet kuvvetlerinin birbirine bağlı etkileşimidir. Flutter: belirli bir hızda kanat veya kuyrukta kendiliğinden büyüyen titreşim; yapıyı saniyeler içinde tahrip edebilir. Diverjans: aerodinamik burulma momenti yapısal rijitliği aştığında kanat bükülür. Kontrol yüzeyi reversal: yüksek hızda kumandanın ters etki yapması.",
   soru:"Flutter hızı nasıl artırılır?",
   cevap:"Yapısal rijitlik artırılarak, ağırlık dengesi sağlanarak veya sweep açısı azaltılarak flutter hızı yükseltilebilir. Tasarım flutter hızının en az yüzde 15 üstünde uçuş zarfından çıkılmalıdır."},

  // ── KALİTE ───────────────────────────────────────────────────────────
  {id:"k31",kategori:"Kalite",ad:"AS9100",en:"AS9100",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Havacılık, uzay ve savunma sanayii için ISO 9001 temel alınarak geliştirilmiş kalite yönetim sistemi standardıdır. Sertifikalı olmak çoğu havacılık tedarik zincirinin kapısını açan zorunlu bir gerekliliktir. Risk yönetimi, konfigürasyon yönetimi ve ilk madde doğrulaması ek gereksinimler arasındadır.",
   soru:"AS9100 ile ISO 9001 arasındaki temel fark nedir?",
   cevap:"ISO 9001 genel endüstri içindir. AS9100 ISO 9001 gerekliliklerini kapsar ve üzerine havacılık-uzay-savunmaya özgü gereksinimler ekler: risk yönetimi, konfigürasyon yönetimi, müşteri odaklı gereklilikler."},
  {id:"k32",kategori:"Kalite",ad:"Kök neden analizi",en:"Root cause analysis",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Bir hatanın belirtiyle değil, temel sebebiyle ilgilenen sistematik yaklaşımdır. 5 Neden yöntemi soruyu art arda beş kez neden diye sorarak gerçek sebebe ulaşmayı hedefler. Balık kılçığı (Ishikawa) diyagramı olası sebepleri kategorilere göre görselleştirir. Her uygunsuzluk raporunda kök neden analizi zorunludur.",
   soru:"5 Neden yönteminin sınırı nedir?",
   cevap:"Doğrusal bir zincir varsayar; oysa çoğu problem çok sebeple oluşur. Soruyu soran kişinin perspektifine göre farklı sonuçlar çıkabilir. Bu yüzden karmaşık sorunlarda balık kılçığı veya FTA ile birlikte kullanılması önerilir."},
  {id:"k33",kategori:"Kalite",ad:"Konfigürasyon yönetimi",en:"Configuration management",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Bir ürünün özelliklerini tanımlayan belgelerin ve bu özelliklerin tutarlılığının sistematik olarak yönetilmesidir. Değişiklik kontrolü süreci olmadan hiçbir parça veya yazılım değiştirilemez. DO-178C ve DO-254 bu yönetimi aviyonik sistemler için zorunlu kılar.",
   soru:"Neden her mühendislik değişikliği resmi onay süreci gerektirir?",
   cevap:"Bir parçanın değişmesi başka birimleri etkileyebilir. Ağırlık merkezi kayabilir, elektromanyetik uyumluluk bozulabilir, yazılım arayüzleri etkilenebilir. Resmi süreç bu etkilerin sistematik incelenmesini güvence altına alır."},
  {id:"k34",kategori:"Kalite",ad:"Uygunsuzluk raporu (NCR)",en:"Non-conformance report",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Bir parça veya sürecin belirlenen gereksinimleri karşılamadığında düzenlenen belgedir. NCR açılınca dört karar verilebilir: iade, yeniden işleme, aynen kullanım (MRB kararıyla) veya hurda. AS9100 kapsamında NCR ve düzeltici faaliyet takibi zorunludur.",
   soru:"Bir parça spesifikasyonun dışına çıkınca neden otomatik hurda edilmez?",
   cevap:"Spesifikasyondaki tolerans zaten bir güvenlik payı içerir. Hafif sapma gerçek kullanımda sorun yaratmayabilir. MRB analizi mühendislik açısından fonksiyonu etkileyip etkilemediğini değerlendirir. Gereksiz hurda hem maliyet hem tedarik süresi açısından ciddi kayıptır."},
  {id:"k35",kategori:"Kalite",ad:"MTBF ve güvenilirlik",en:"MTBF and reliability",mulakat:true,branslar:["ucak","uzay"],
   tanim:"MTBF (Mean Time Between Failures) ardışık iki arıza arasındaki ortalama çalışma süresidir. R(t) = e^(-t/MTBF) formülüyle güvenilirlik hesaplanır. Kritik havacılık sistemleri için arıza olasılığı uçuş saati başına 10⁻⁹ gibi çok küçük değerlere indirilmek zorundadır. Yedeklilik güvenilirliği artırmanın temel yoludur.",
   soru:"Yedekli sistemde güvenilirlik nasıl hesaplanır?",
   cevap:"İki paralel bileşenin her birinin arızalanma ihtimali q ise sistemin arızalanma ihtimali q² dir, güvenilirlik 1-q² olur. Seri sistemde ise güvenilirlikler çarpılır, bu yüzden seri elemanlar güvenilirliği düşürür."},
  {id:"k36",kategori:"Kalite",ad:"Yazılım güvencesi: DO-178C",en:"DO-178C",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Havacılık yazılımlarının güvenlik sınıfına göre geliştirilmesini ve doğrulanmasını düzenleyen standarttır. A dan E ye beş düzey vardır. A düzeyi yazılım arızası felakete yol açabilecek sistemlerde kullanılır. Uçuş kontrol bilgisayarları ve motor kontrol sistemleri A düzeyi yazılım içerir.",
   soru:"DO-178C ile yazılım geliştirmek ticari yazılımdan neden farklıdır?",
   cevap:"Her gereksinim izlenebilir olmalı, her kod satırı test edilmeli ve test kapsamı (coverage) ölçülmelidir. A düzeyinde MC/DC (modified condition/decision coverage) şartı aranır. Bu süreç ticari yazılıma göre 10-100 kat daha maliyetlidir."},

  // ── ÖLÇME ────────────────────────────────────────────────────────────
  {id:"k37",kategori:"Ölçme",ad:"Mikrometre",en:"Micrometer",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Genellikle 0,01 mm hassasiyetle ölçüm yapabilen hassas uzunluk ölçme aletidir. 25 mm aralıklarla üretilir. Abbe prensibine uymaktadır: ölçülen boyut ve referans ekseni hizalıdır. Bu sayede kumpastaki paralaks hatasından muaf kalır.",
   soru:"Kumpas ve mikrometre aynı anda kullanıldığında hangisi önce tercih edilir?",
   cevap:"Gerekli hassasiyet ve ölçme aralığı belirler. Mikrometre daha hassastır ancak dar aralıklıdır. Kumpas daha geniş aralıklı ve çok amaçlıdır. İlk ölçümde kumpasla boyut belirlenir, hassas kontrol için mikrometre kullanılır."},
  {id:"k38",kategori:"Ölçme",ad:"Gerinim ölçer",en:"Strain gauge",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Malzeme yüzeyine yapıştırılan ve uzama ile kısalmayı elektriksel direnç değişimi olarak ölçen sensördür. Wheatstone köprüsü devresiyle direnç değişimi hassas voltaj sinyaline çevrilir. Uçak yapı testlerinde, kanat yük ölçümlerinde ve roket motor testlerinde yaygın kullanılır.",
   soru:"Gerinim ölçer neden köprü devresiyle okunur?",
   cevap:"Gerinim altındaki direnç değişimi çok küçüktür. Wheatstone köprüsü bu küçük değişimi büyük bir voltaj farkına dönüştürür. Ayrıca köprü konfigürasyonu sıcaklık değişiminden kaynaklanan hatayı iptal eder."},
  {id:"k39",kategori:"Ölçme",ad:"Pitot-statik sistem",en:"Pitot-static system",mulakat:true,branslar:["ucak"],
   tanim:"Uçağın hava hızını, irtifasını ve tırmanma hızını ölçen sistemdir. Pitot tüpü toplam basıncı, statik portlar statik basıncı ölçer. Büyük uçaklar yedek pitot-statik sistemi taşır. Air France 447 kazasında pitot buzlanması kritik bir rol oynamıştır.",
   soru:"Altimetre neden GPS ile aynı yüksekliği göstermez?",
   cevap:"Altimetre basınç ölçer ve standart atmosfer modeline göre irtifayı hesaplar. GPS ise geometrik yüksekliği ölçer. Havacılıkta basınç irtifası kullanılır çünkü tüm uçaklar aynı referansla uçar."},
  {id:"k40",kategori:"Ölçme",ad:"Koordinat ölçüm makinesi (CMM)",en:"Coordinate measuring machine",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Üç eksende hassas konum ölçümü yaparak karmaşık geometrilerin boyutsal kontrolünü sağlayan makinedir. Dokunmalı prob veya lazer tarayıcıyla çalışır. Ölçüm ortamının sıcaklığı 20±1 °C olarak kontrol edilmelidir; ısıl genleşme sonuçları etkiler.",
   soru:"CMM ölçümü neden kontrollü sıcaklıkta yapılmalıdır?",
   cevap:"Metaller ısıl genleşme katsayısına göre boyut değiştirir. Çelik için yaklaşık 11 µm/m/°C dir. Havacılık toleransları µm mertebesinde olduğundan 1-2 °C fark ölçüm hatasını tolerans aralığından büyük yapabilir."},
  {id:"k41",kategori:"Ölçme",ad:"GD&T",en:"Geometric Dimensioning and Tolerancing",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Parçanın şeklini, yönelimini, konumunu ve salınımını sayısal değerlerle tanımlayan sembolik dil sistemidir. ASME Y14.5 ve ISO 1101 başlıca standarttır. GD&T olmadan sadece ölçü toleransı vermek fonksiyonel gereksinimleri yetersiz ifade eder.",
   soru:"GD&T olmadan sadece ölçü toleransı vermenin sorunu nedir?",
   cevap:"Koordinat toleransı kare alan tanımlar; GD&T konum toleransı dairesel alan tanımlar. Dairesel alan daha büyüktür, üretim payı artar ve maliyet düşer. Ayrıca GD&T fonksiyonel gereksinimi daha açık ifade eder."},
  {id:"k42",kategori:"Ölçme",ad:"Kalibrasyon ve izlenebilirlik",en:"Calibration and traceability",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Kalibrasyon, bir ölçüm aletinin çıktısını bilinen bir referansa karşı karşılaştırıp düzeltme miktarını belirleme işlemidir. İzlenebilirlik, her ölçüm aletinin ulusal veya uluslararası standartlara kesintisiz belgelenmiş bir zincirle bağlı olması demektir. Türkiye de UME bu zincirin tepesindedir.",
   soru:"Kalibrasyonun süresi dolmuş bir aletle ölçtün ve sonuç limitlerin içinde. Bu parçayı kullanabilir misin?",
   cevap:"Hayır. Süresi dolmuş aletle yapılan tüm ölçümler şüpheli sayılır. Parçaları geri çağırıp geçerli aletle yeniden ölçmek gerekir."},
  {id:"k43",kategori:"Ölçme",ad:"Ölçüm belirsizliği",en:"Measurement uncertainty",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Her ölçüm sonucunun gerçek değerin etrafında bir aralıkla ifade edilmesidir. Genişletilmiş belirsizlik U = k·uc formülüyle hesaplanır; k kapsama faktörüdür. Ölçüm sonucu 25,42 ± 0,05 mm şeklinde rapor edilir. Toleransın ölçüm belirsizliğinin en az 4 katı olması önerilir.",
   soru:"Tolerans 0,02 mm olan bir parçayı 0,01 mm belirsizlikli aletle ölçmek doğru mudur?",
   cevap:"Hayır, yeterli değil. Belirsizlik toleransın en az dörtte biri olmalıdır. Bu durumda parça gerçekte limitlerin içinde olsa da ölçüm sonucu dışarıda gösterebilir. Daha hassas aletle ölçmek gerekir."},

  // ── TASARIM ──────────────────────────────────────────────────────────
  {id:"k44",kategori:"Tasarım",ad:"V modeli",en:"V model",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Sistem geliştirme sürecini sol tarafta gereksinim ve tasarım, sağ tarafta doğrulama ve geçerleme aşamalarıyla V şeklinde gösteren çerçevedir. Her sol taraf faaliyetinin karşısında bir test faaliyeti bulunur. Havacılık ve savunma projelerinde standart süreç modelidir.",
   soru:"Doğrulama (verification) ile geçerleme (validation) arasındaki fark nedir?",
   cevap:"Doğrulama sistemi doğru yaptık mı sorusunu yanıtlar, yani spesifikasyona uygunluğu kontrol eder. Geçerleme ise doğru sistemi yaptık mı sorusunu yanıtlar, yani müşteri ihtiyacını karşılayıp karşılamadığını dener."},
  {id:"k45",kategori:"Tasarım",ad:"Emniyet katsayısı",en:"Factor of safety",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Tasarım yükünün malzemenin dayanımına veya kritik yüke oranıdır. Belirsizlikleri, malzeme değişkenliğini ve imalat kusurlarını karşılar. Sivil havacılıkta limit yük emniyet katsayısı 1,5 olarak tanımlanmıştır. Uzay yapılarında ağırlık kritik olduğundan emniyet katsayıları çok daha düşük tutulur.",
   soru:"Emniyet katsayısını yüksek tutmak neden her zaman iyi değildir?",
   cevap:"Emniyet katsayısı yüksek tutulunca ağırlık artar. Uçakta her kilogram ekstra yakıt tüketimi ve azalan faydalı yük demektir. İyi mühendislik yeterli emniyeti en az ağırlıkla sağlamaktır."},
  {id:"k46",kategori:"Tasarım",ad:"Sistem mühendisliği",en:"Systems engineering",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Karmaşık sistemlerin gereksinimlerinin belirlenmesinden operasyona kadar tüm yaşam döngüsünü yönetmeye odaklanan disiplinlerarası yaklaşımdır. Gereksinim analizi, fonksiyon dağılımı, arayüz yönetimi ve ödünleşim çalışmaları sistemin mühendisliğinin çekirdeğidir.",
   soru:"Bir alt sistem kendi başına mükemmel çalışsa bile sistemin tamamı neden başarısız olabilir?",
   cevap:"Arayüzler ve entegrasyon sorunları nedeniyle. Her alt sistem kendi başına test edilmiş olabilir ama birlikte çalıştıklarında elektromanyetik girişim, termal yük paylaşımı veya yazılım zamanlama çakışması sorunlar çıkarabilir."},
  {id:"k47",kategori:"Tasarım",ad:"Ödünleşim analizi",en:"Trade study",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Bir tasarım kararında birden fazla seçeneği birden fazla kriter açısından karşılaştıran sistematik yöntemdir. Her kritere ağırlık verilir, her seçenek puanlanır ve ağırlıklı toplam hesaplanır. Motor seçimi, malzeme seçimi ve sistem mimarisi kararları ödünleşim analizleriyle desteklenir.",
   soru:"Ödünleşim analizinde en yüksek puanı alan seçenek her zaman seçilmeli midir?",
   cevap:"Zorunlu değil. Ağırlıklar değiştirilirse farklı seçenek öne çıkabilir. Bu yüzden duyarlılık analizi yapılır: ağırlıklar makul aralıkta değiştirildiğinde sonuç değişiyor mu diye bakılır."},
  {id:"k48",kategori:"Tasarım",ad:"Arayüz kontrol belgesi (ICD)",en:"Interface control document",mulakat:true,branslar:["ucak","uzay"],
   tanim:"İki sistem veya alt sistem arasındaki her türlü arayüzü (mekanik, elektriksel, termal, yazılım, veri) tanımlayan belgedir. ICD iki tarafça imzalanır; değişiklik ancak iki tarafın onayıyla yapılabilir. Savunma projelerinde ICD tutarsızlıkları entegrasyon aşamasında ciddi gecikmelere yol açabilir.",
   soru:"ICD olmadan iki alt sistem neden entegre edilemez?",
   cevap:"Her ekip kendi varsayımlarıyla tasarım yapar. Biri 28V DC beklerken diğeri 115V AC verebilir; biri 10 mm delik açarken diğeri 12 mm cıvata kullanabilir. ICD bu beklentileri önceden hizalar."},
  {id:"k49",kategori:"Tasarım",ad:"PDR ve CDR",en:"Preliminary and Critical Design Review",mulakat:true,branslar:["ucak","uzay"],
   tanim:"PDR ön tasarımın gereksinimleri karşılanmakta mı sorusunu yanıtlar. CDR detay tasarımın üretim için olgunlaşıp olgunlaşmadığını değerlendirir. Bu eşikler geçilmeden bir sonraki aşamaya geçilmez. NASA ve savunma programlarında resmi süreçlerdir.",
   soru:"CDR dan sonra tasarım değişikliği yapılamaz mı?",
   cevap:"Teknik olarak yapılabilir ama resmi değişiklik süreci gerektirir ve maliyeti artar. CDR sonrası değişiklikler ayrıca izlenir. Büyük değişiklikler bazen CDR in tekrarlanmasını gerektirir."},
  {id:"k50",kategori:"Tasarım",ad:"Ağırlık ve denge raporu",en:"Weight and balance report",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Bir uçak veya uzay aracının kütlesini ve ağırlık merkezinin konumunu belgeleyen raporlardır. Uçakta ağırlık merkezi (CG) her uçuş koşulunda izin verilen aralıkta kalmalıdır. Her bileşenin kütlesi ve konumu takip edilir; tasarım sürecinde bütçe kontrolü yapılır.",
   soru:"Uçak arka CG sınırını aşarsa ne olur?",
   cevap:"Uçak boylamasına kararsız hale gelir. Pilot küçük bozuntuları düzeltemez. Fly-by-wire sistemli uçaklar bu durumu sınırlı ölçüde yönetebilir; ama mekanik kontrollü uçaklarda kontrolden çıkma riski artar."},
  {id:"k51",kategori:"Tasarım",ad:"Ömür döngüsü maliyeti",en:"Life cycle cost (LCC)",mulakat:false,branslar:["ucak","uzay"],
   tanim:"Bir sistemin tasarım, üretim, operasyon, bakım ve imha aşamalarındaki toplam maliyetidir. Satın alma fiyatı genellikle ömür döngüsü maliyetinin küçük bir kısmıdır. Operasyon ve bakım çoğu zaman çok daha fazla tutar.",
   soru:"Satın alma fiyatı düşük olan savunma sistemi her zaman daha ekonomik midir?",
   cevap:"Hayır. Bakım, yakıt, yedek parça ve modernizasyon maliyetleri toplamda çok daha büyük olabilir. 40 yıl operasyon yapacak bir savaş uçağı için LCC analizi, ucuz ama bakım yoğun sistemi daha pahalı gösterebilir."},

  // ── HAVACILlK ────────────────────────────────────────────────────────
  {id:"k52",kategori:"Havacılık",ad:"Reynolds sayısı",en:"Reynolds number",mulakat:true,branslar:["ucak"],
   tanim:"Atalet kuvvetlerinin viskoz kuvvetlere oranını gösteren boyutsuz sayıdır: Re = ρVL/µ. Düşük Re de akış laminar, yüksek Re de turbülanslıdır. Rüzgâr tüneli testlerinde aynı Re sağlanmazsa sonuçlar gerçekle örtüşmez.",
   soru:"Küçük ölçekli rüzgâr tüneli modelinde neden tam ölçek Re sağlamak zordur?",
   cevap:"Model küçüldükçe aynı Re için ya hızın ya da yoğunluğun artması gerekir. Hızı artırınca Mach sayısı değişir. Bu yüzden basınçlı veya kriojenik rüzgâr tünelleri kullanılarak yoğunluk artırılır."},
  {id:"k53",kategori:"Havacılık",ad:"Mach sayısı ve sıkıştırılabilirlik",en:"Mach number",mulakat:true,branslar:["ucak"],
   tanim:"Akış hızının yerel ses hızına oranıdır: M = V/a. M < 0,3 sıkıştırılamaz, 0,3-0,8 düşük sıkıştırılabilir, 0,8-1,2 transonik, 1,2-5 süpersonik, 5 ve üstü hipersonik. Transonik bölgede hem ses altı hem üstü akış bölgeleri aynı anda oluşur.",
   soru:"Uçak transonik hızda neden güçlük çeker?",
   cevap:"Kanadın üzerinde ses hızına ulaşan bölgeler oluşur ve şok dalgaları meydana gelir. Bu şoklar sürüklemeyi dramatik artırır (dalga sürüklenmesi) ve akış ayrılmasına yol açabilir."},
  {id:"k54",kategori:"Havacılık",ad:"Kaldırma katsayısı ve polâr",en:"Lift coefficient and polar",mulakat:true,branslar:["ucak"],
   tanim:"Kaldırma katsayısı CL = L / (½ρV²S) formülüyle tanımlanır. Hücum açısıyla doğrusal artar, stall da düşer. L/D oranı aerodinamik verimlilik ölçütüdür. Modern yolcu uçakları L/D ~ 18, uzay mekiği L/D ~ 1 dir.",
   soru:"İniş sırasında yüksek kaldırma katsayısı neden tek başına yeterli değildir?",
   cevap:"Yüksek CL beraberinde yüksek CD getirir. Bu yüzden motor gücü gereklidir. Tüm motorlar dursa motor olmadan iniş tasarım gereksinimi tam da bu yüzden kritiktir."},
  {id:"k55",kategori:"Havacılık",ad:"Stall ve stall uyarı sistemleri",en:"Stall warning",mulakat:true,branslar:["ucak"],
   tanim:"Kritik hücum açısında kanattaki akış ayrılır ve kaldırma düşer. Titreklik (stick shaker) uyarı verir, itici (stick pusher) burnu otomatik aşağı iter. MCAS sistemi Boeing 737 MAX kazalarında bu kavramın ne kadar kritik olduğunu gösterdi.",
   soru:"Ters (inverted) stall neden tehlikelidir?",
   cevap:"Normal stall da pilot burnu aşağı alarak kurtarır. Ters uçuşta stall da ise burnu yukarı almak gerekir. Eğitim almamış pilot alışkanlıkla burnu aşağı alır ve durumu kötüleştirir."},
  {id:"k56",kategori:"Havacılık",ad:"İniş takımı",en:"Landing gear",mulakat:true,branslar:["ucak"],
   tanim:"Uçağın yerde hareketini, kalkış ve iniş yüklerini taşıyan sistemdir. Tricycle ve taildragger ana konfigürasyonlardır. Katlanır iniş takımı sürüklemeyi azaltmak için kanat içine çekilir. İnişte kaldırma kuvvetinin ani kaybı ve lastik teması dinamikleri kritik yükleri oluşturur.",
   soru:"Neden büyük uçaklarda çok sayıda tekerlek kullanılır?",
   cevap:"Pist yüzey basıncını sınırlamak için. Havaalanı pistleri belirli tekil yük (PCN) değerleri için tasarlanmıştır. A380 de bu yüzden 22 ana tekerlek ve 2 ön tekerlek kullanılmıştır."},
  {id:"k57",kategori:"Havacılık",ad:"ETOPS",en:"Extended-range Twin-engine Operations",mulakat:true,branslar:["ucak"],
   tanim:"Çift motorlu yolcu uçaklarının en yakın uygun havaalanından belirli bir süre uzakta uçmasına izin veren sertifikasyondur. ETOPS-180 tek motorla 180 dakika uzakta uçabilmek demektir. Bu sayede okyanus aşırı doğrudan uçuşlar mümkündür.",
   soru:"ETOPS olmadan çift motorlu uçak neden okyanus aşamaz?",
   cevap:"Geçmiş kurallarda çift motorlu uçak her zaman 60 dakika içinde bir havaalanına inebilecek rotayı izlemeliydi. Bu okyanusun büyük kesimini uçulmaz yapıyordu. ETOPS motor güvenilirliğinin kanıtlanmasıyla bu mesafeyi uzattı."},
  {id:"k58",kategori:"Havacılık",ad:"Yüksek irtifanın insan üzerine etkileri",en:"Altitude physiology",mulakat:true,branslar:["ucak"],
   tanim:"İrtifa arttıkça hava basıncı ve oksijen parsiyel basıncı düşer. Hipoksi 3000 m den itibaren başlar, 5000-6000 m de faydalı bilinç süresi 30 dakikaya düşer. Hızlı tırmanma ve anlık kabin basıncı kaybı pilotlar için ciddi risk oluşturur.",
   soru:"Savaş pilotları neden özel baskı elbisesi giyer?",
   cevap:"Yüksek irtifada kabin basıncı kaybı anlık olabilir. Baskı elbisesi yeterli oksijen basıncını vücuda sağlar ve hipoksiye karşı korur."},
  {id:"k59",kategori:"Havacılık",ad:"Kabin basınçlandırma",en:"Pressurization",mulakat:true,branslar:["ucak"],
   tanim:"Yüksek irtifada kabin içini yaşanabilir basınçta tutan sistemdir. Türbin motoru kompresöründen çekilen hava kabin basıncını sağlar. Kabin yüksekliği genellikle 6000-8000 feet eşdeğeri tutulur. Her basınçlandırma çevrimi gövdede yorulma stresine yol açar.",
   soru:"Neden tam deniz seviyesi basıncı değil daha düşük bir kabin yüksekliği hedeflenir?",
   cevap:"Tam deniz seviyesi basıncı tutmak gövdeye çok büyük basınç farkı yükler ve gövdeyi ağırlaştırır. Seçilen kabin yüksekliği sağlık açısından yeterli oksijen sunarken yapısal yük ve ağırlık dengesini sağlar."},
  {id:"k60",kategori:"Havacılık",ad:"Fly-by-wire",en:"Fly-by-wire (FBW)",mulakat:true,branslar:["ucak"],
   tanim:"Pilotun kumandalarını mekanik veya hidrolik bağlantı yerine elektronik sinyal olarak uçuş bilgisayarına gönderdiği sistemdir. Uçuş zarfı koruması, ağırlık tasarrufu ve bakım kolaylığı avantajları sağlar. Airbus A320 ilk dijital FBW uçağıdır; F-16 ise ilk dijital FBW savaş uçağıdır.",
   soru:"FBW sisteminde yazılım hatası neden çok kritiktir?",
   cevap:"Mekanik sistemde pilot bir arıza durumunda yedek kanalı deneyebilir. FBW de yazılım hatası tüm kontrol yüzeylerini etkileyebilir. Bu yüzden üçlü veya dörtlü yedekli bilgisayar sistemi kullanılır."},
  {id:"k61",kategori:"Havacılık",ad:"Hipersonik uçuş",en:"Hypersonic flight",mulakat:false,branslar:["ucak"],
   tanim:"Mach 5 ve üzeri hızlarda uçuştur. Bu hızlarda şok ısıtması çok şiddetlenir ve geleneksel türbin motorları çalışamaz. Scramjet motoru sadece bu hızlarda verimli çalışır. Atmosfere giren uzay araçları da hipersonik bölgeyi geçer.",
   soru:"Scramjet neden düşük hızda çalışamaz?",
   cevap:"Scramjet de hava giriş kanalından gelen hava süpersonik kalarak yanma odasına girer. Bunun için motorun önceden Mach 4-5 hıza ulaşmış olması gerekir. Bu başlangıç hızı roket veya başka bir motor tarafından sağlanmalıdır."},
  {id:"k62",kategori:"Havacılık",ad:"Uçuş testi (flight test)",en:"Flight testing",mulakat:true,branslar:["ucak"],
   tanim:"Bir uçağın tasarım gereksinimlerini gerçek uçuş koşullarında doğrulama sürecidir. Test pilotu ve test mühendisi birlikte çalışır. Uçuş zarfı genişletme, stall, spin, motor durma ve yapı yükü ölçümü başlıca kategorilerdir. Uçuşlardaki her parametre telemetriyle yere iletilir.",
   soru:"Simülasyon her şeyi doğrulayabilseydi neden flight test yapılır?",
   cevap:"Simülasyon modelin doğruluğu kadar güvenilirdir. Gerçek atmosfer, malzeme toleransları ve beklenmedik etkileşimler simülasyonda tam yansımaz. Örneğin yüksek hücum açısında akış ayrılması simüle edilebilir ama gerçek uçuşta farklı davranabilir."},

  // ── UZAY ─────────────────────────────────────────────────────────────
  {id:"k63",kategori:"Uzay",ad:"Delta-v",en:"Delta-v (Δv)",mulakat:true,branslar:["uzay"],
   tanim:"Bir uzay aracının yörünge değiştirmek için harcadığı toplam hız değişimidir. Uzay görevlerinin yakıt bütçesinin temel birimidir. Tsiolkovsky denklemi Δv = Isp·g₀·ln(m₀/mf) bağıntısıyla hesaplanır. Dünya yüzeyinden alçak yörüngeye çıkmak yaklaşık 9,5 km/s Δv gerektirir.",
   soru:"Aynı Δv için daha fazla yük taşımanın yolu nedir?",
   cevap:"Özgül itki artırılırsa aynı Δv için daha az yakıt harcanır, daha fazla faydalı yük taşınır. Alternatif olarak çok kademeli roket kullanılarak boş kütle erken atılır."},
  {id:"k64",kategori:"Uzay",ad:"Yörünge türleri",en:"Orbit types",mulakat:true,branslar:["uzay"],
   tanim:"LEO (200-2000 km) ISS burada. MEO (2000-35786 km) GPS uyduları burada. GEO (35786 km) Dünya ile birlikte döner, haberleşme uyduları. SSO güneş eşzamanlı, yer gözlem uyduları. Molniya elips yörüngede kuzey yarımküreyi gözlemler.",
   soru:"GPS uyduları neden LEO de değil MEO de bulunur?",
   cevap:"LEO de yörünge periyodu yaklaşık 90 dakikadır ve uydu hızla geçer. MEO de yörünge periyodu 12 saat olup her bölgede aynı anda görünen uydu sayısı istikrarlı kalır."},
  {id:"k65",kategori:"Uzay",ad:"Serbest düşüş ve mikro yerçekimi",en:"Free fall and microgravity",mulakat:true,branslar:["uzay"],
   tanim:"ISS da yerçekimi deniz seviyesinin yaklaşık yüzde 90 ı kadardır. Astronotların yüzmesinin sebebi yerçekimsizlik değil, istasyonun Dünya ya düşmesidir. Yatay hızları yeterince yüksek olduğu için yörüngede kalmaya devam ederler. Uzun süreli mikro yerçekimi kemik yoğunluğu kaybı ve kas zayıflamasına yol açar.",
   soru:"Dünya etrafındaki yörüngede uzay aracı neden yakıt harcamaz?",
   cevap:"Alçak yörüngede atmosfer sürtünmesi yavaşlatır ve zaman zaman itici kullanılır. Ama bunun dışında yerçekimi ve atalet kuvveti dengededir, ek itki gerekmez."},
  {id:"k66",kategori:"Uzay",ad:"CubeSat",en:"CubeSat",mulakat:true,branslar:["uzay"],
   tanim:"10×10×10 cm birim (1U) üzerine kurulu standart küçük uydu formatıdır. Ticari hazır elektronik bileşenler ve standart arayüzler maliyeti düşürür. Üniversiteler ve küçük firmalar CubeSat ile uzay erişimini demokratikleştirmiştir.",
   soru:"CubeSat neden büyük savunma uydularının yerini alamaz?",
   cevap:"Küçük hacimleri güç, haberleşme anteni ve optik aperture kısıtlar. Büyük teleskop veya radar gerektiren görevler için fiziksel boyut şarttır."},
  {id:"k67",kategori:"Uzay",ad:"Uzay hava durumu",en:"Space weather",mulakat:false,branslar:["uzay"],
   tanim:"Güneş aktivitesinin uzay ortamına ve Dünya ya yakın bölgelere etkileridir. Güneş fırtınaları radyasyon kuşaklarını yoğunlaştırır ve iletişimi kesebilir. GPS sinyali iyonosfer kaynaklı gecikmeden etkilenir.",
   soru:"Geostationary uydular neden LEO uydularından daha fazla radyasyona maruz kalır?",
   cevap:"Van Allen radyasyon kuşakları MEO dan GEO ya kadar uzanır. Alçak yörüngede Dünya nın manyetik alanı önemli bir kalkan sağlar. GEO da bu koruma çok daha zayıftır."},
  {id:"k68",kategori:"Uzay",ad:"Yeniden kullanılabilir roketler",en:"Reusable launch vehicles",mulakat:true,branslar:["uzay"],
   tanim:"Geleneksel roketler tek kullanımlıktır ve fırlatma başına maliyeti yüksektir. SpaceX Falcon 9 birinci kademesi dikey inişle geri döner. Boş birinci kademeyi geri getirmek fırlatma maliyetini önemli ölçüde azaltır.",
   soru:"Yeniden kullanım sayısı arttıkça güvenilirlik nasıl etkilenir?",
   cevap:"Her uçuşta yapısal yorulma ve ısıl döngü birikir. SpaceX her geri dönen kademede kapsamlı muayene yapar. Kaç uçuşta bir büyük bakım gerektiği operasyonel deneyimle belirlenmektedir."},
  {id:"k69",kategori:"Uzay",ad:"Uzay çöpü ve Kessler sendromu",en:"Space debris and Kessler syndrome",mulakat:true,branslar:["uzay"],
   tanim:"Yörüngede 10 cm üstü 23.000 den fazla izlenen insan yapımı nesne bulunmaktadır. Kessler sendromu: zincirleme çarpışmalar yörüngeyi kullanılamaz hale getirebilir. 25 yıl kuralı: uydu ömrü sona erince 25 yıl içinde yörüngeden çıkmalıdır.",
   soru:"Uzay çöpünden korunmak için uydular ne yapabilir?",
   cevap:"Küçük parçalar için kalkan zırh kullanılır. Büyük parçalar için takip verileri kullanılarak manevra yapılır. Tasarım aşamasında yakıt deposu veya batarya ömür sonunda boşaltılır, patlama riski azaltılır."},
  {id:"k70",kategori:"Uzay",ad:"Güç sistemi: güneş paneli ve batarya",en:"Solar panel and battery",mulakat:true,branslar:["uzay"],
   tanim:"Uyduların temel güç kaynağı güneş panelleridir. Güneş tutulması sırasında batarya güç sağlar. Güneş paneli verimi ışınım hasarıyla yıllarca düşer; bu yaşlanma tasarımda hesaba katılır.",
   soru:"Jüpiter çevresindeki uzay araçları neden güneş paneli değil RTG kullanır?",
   cevap:"Güneş ışığının şiddeti mesafenin karesiyle azalır. Jüpiter yörüngesinde güneş ışığı Dünya dakinin yaklaşık 1/27 si kadardır. RTG ısı enerjisini yakıt bağımsız olarak elektriğe dönüştürür."},
  {id:"k71",kategori:"Uzay",ad:"Yörüngeden çıkış ve yeniden giriş",en:"Deorbit and reentry",mulakat:true,branslar:["uzay"],
   tanim:"Yörüngeden çıkış için itici ateşlenerek hız azaltılır ve araç atmosfere girer. Giriş açısı kritiktir: çok sığ olursa araç atmosferden sekip uzaya geri döner, çok dik olursa aşırı ısı ve yük oluşur.",
   soru:"Giriş açısının çok sığ olması neden tehlikelidir?",
   cevap:"Frenleme yetersiz kalır ve araç tekrar uzaya sekebilir. Eğer yakıt bitmişse bir daha giriş denemesi yapılamaz. Gemini ve Apollo kapsülleri bu yüzden dar bir giriş koridorunu hassasça hedeflemiştir."},

  // ── KONTROL VE SİSTEM ─────────────────────────────────────────────────
  {id:"k72",kategori:"Kontrol ve Sistem",ad:"PID kontrol",en:"PID control",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Oransal (P), integral (I) ve türevsel (D) terimlerin toplamından oluşan en yaygın geri beslemeli kontrolördür. P hatayı azaltır, I kalıcı hatayı sıfırlar, D değişim hızına tepki verir ve aşımı azaltır. PID kazanç ayarı (tuning) pratiğin en kritik adımıdır.",
   soru:"PID nin I terimi olmasa ne olur?",
   cevap:"Sisteme sabit bir bozunum etki ettiğinde kalıcı hata (steady-state error) kalır. İnsansız hava aracı istenen irtifada sabit kalmak yerine biraz altında ya da üstünde sürünür. I terimi bu hatayı zamanla birikterir ve sıfırlar."},
  {id:"k73",kategori:"Kontrol ve Sistem",ad:"Durum uzayı gösterimi",en:"State space representation",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Çok girişli çok çıkışlı sistemleri matrisle ifade eden modern kontrol teorisi çerçevesidir. ẋ = Ax + Bu, y = Cx + Du denklemleriyle tanımlanır. Transfer fonksiyonu bu gösterimden türetilebilir ama durum uzayı daha geneldir.",
   soru:"Transfer fonksiyonu ve durum uzayı arasındaki fark nedir?",
   cevap:"Transfer fonksiyonu tek giriş tek çıkış (SISO) ve doğrusal sistemler için uygundur. Durum uzayı MIMO ve zamanla değişen sistemlere de uygulanabilir. Bilgisayar simülasyonunda durum uzayı matris işlemi nedeniyle çok daha pratiktir."},
  {id:"k74",kategori:"Kontrol ve Sistem",ad:"Kalman filtresi",en:"Kalman filter",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Gürültülü sensör ölçümlerinden sistemin durumunu en iyi şekilde tahmin eden özyinelemeli algoritmadır. Yön belirleme sistemlerinde jiroskop ve ivmeölçer verilerini birleştirmek, GPS ve INS füzyonu bu filtrenin en yaygın uygulamalarıdır. Apollo navigasyon bilgisayarında ilk kez uzayda kullanılmıştır.",
   soru:"GPS sinyali kesildiğinde Kalman filtresi ne yapar?",
   cevap:"Ölçüm olmadan sadece tahmin adımını çalıştırır. Yani sistem modeliyle durumu ilerletir ama güncelleme yapamaz. Hata zamanla birikir; bunu INS drifti olarak biliriz."},
  {id:"k75",kategori:"Kontrol ve Sistem",ad:"Otopilot modları",en:"Autopilot modes",mulakat:true,branslar:["ucak"],
   tanim:"Modern uçak otopilotları çok sayıda mod içerir: irtifa tut, hız tut, rota tut, ILS yaklaşma modu, VNAV/LNAV, otomatik kalkış ve iniş. Her mod farklı denetleyici ve geri besleme döngüsü kullanır. Mod geçişleri yumuşak yapılmalıdır.",
   soru:"Neden bazı durumlarda otopilot yerine el ile uçuş tercih edilir?",
   cevap:"Alışılmadık tutumlardan kurtarma, kısa pist inişleri ve yoğun hava trafiğinde esneklik için. Ayrıca pilotların el becerilerini korumak amacıyla el uçuşu yapılır. El uçuşu yapmayan pilotun refleksleri zayıflayabilir."},
  {id:"k76",kategori:"Kontrol ve Sistem",ad:"İnsan-makine arayüzü (HMI)",en:"Human-machine interface",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Pilotun sistemle etkileştiği her türlü fiziksel ve yazılım arayüzüdür. Bilgi yükü azaltmak için öncelikli bilgiler öne çıkarılır. Mod karışıklığı (mode confusion) fly-by-wire ve otopilot sistemlerinde ciddi kaza sebebidir.",
   soru:"Mode confusion nedir ve nasıl önlenir?",
   cevap:"Pilot otopilotun hangi modda olduğunu sanıyorken gerçekte başka bir modda olmasıdır. Önleme: net ve tutarlı mod göstergeleri, sesli uyarılar ve pilot eğitimi. Tasarımda beklenmedik mod değişikliği ilkesi benimsenir."},
  {id:"k77",kategori:"Kontrol ve Sistem",ad:"Gereksinim yönetimi",en:"Requirements management",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Sistemin ne yapması gerektiğini tanımlayan gereksinimlerin oluşturulması ve yönetilmesidir. Her gereksinim benzersiz kimliğe sahip olmalı, tek bir şeyi ifade etmeli, test edilebilir ve kaynağına izlenebilir olmalıdır. Belirsiz gereksinim projenin sonunda büyük anlaşmazlık ve maliyet artışı kaynağıdır.",
   soru:"Kötü yazılmış bir gereksinim örneği nedir?",
   cevap:"Sistem hızlı tepki vermelidir kötü bir gereksinimdir çünkü hızlı ölçülemez. Doğrusu: Sistem girişten en fazla 50 ms içinde çıkış üretmelidir. Test edilebilir, tek bir şey ifade eder ve ölçülebilir."},
  {id:"k78",kategori:"Kontrol ve Sistem",ad:"Elektromanyetik uyumluluk (EMC)",en:"Electromagnetic compatibility",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Elektronik sistemlerin hem elektromanyetik girişim yaymaması hem de dışarıdan gelen girişime dayanması gereksinimidir. Havacılıkta DO-160 standardı çevresel test gereksinimlerini tanımlar. Kablo yönlendirme, topraklama tasarımı ve filtreleme EMC nin temel araçlarıdır.",
   soru:"Kompozit uçak gövdesi şimşeğe karşı neden ek koruma gerektirir?",
   cevap:"Metal gövde Faraday kafesi etkisi yapar. Karbon fiber iletken olsa da iletkenliği metalden düşüktür. Bu yüzden karbon fiber gövdelere metal ağ veya şerit gömülür."},

  // ── ÜRETİM ───────────────────────────────────────────────────────────
  {id:"k79",kategori:"Üretim",ad:"CNC işleme",en:"CNC machining",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Bilgisayar Sayısal Kontrolü ile torna ve freze tezgâhlarını otomatik yönetme yöntemidir. G-kodu makine hareketlerini tanımlar. 5 eksenli işleme karmaşık kanat profilleri ve motor bileşenleri gibi geometrileri tek bağlamada üretir.",
   soru:"5 eksenli işlemenin 3 eksenli işlemeden farkı nedir?",
   cevap:"3 eksenli işlemede parçanın birden fazla pozisyonda bağlanması gerekebilir; her bağlama hata ekler. 5 eksenli işlemede parça yatırılıp döndürülebildiğinden karmaşık geometriler tek bağlamada tamamlanır."},
  {id:"k80",kategori:"Üretim",ad:"Eklemeli imalat",en:"Additive manufacturing",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Malzemeyi katman katman ekleyerek parça üreten yöntemler ailesidir. Metal eklemeli imalatta SLM ve EBM en yaygın yöntemlerdir. GE nin CFM LEAP motorundaki yakıt memesi 20 parça yerine tek parça olarak üretilmiştir.",
   soru:"Eklemeli imalatın geleneksel işlemeye göre dezavantajı nedir?",
   cevap:"Yüzey pürüzlülüğü genelde yüksektir ve son işleme gerektirir. Üretim hızı düşüktür. Sertifikasyon süreci karmaşıktır çünkü her baskı partisinin mekanik özelliği değişkenlik gösterebilir."},
  {id:"k81",kategori:"Üretim",ad:"Dövme",en:"Forging",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Metalin kalıplar arasında basınç uygulanarak şekillendirilmesidir. Döküme göre daha iyi mekanik özellikler sağlar çünkü tane yapısı parçanın şekline göre akar. Uçak iniş takımları, bağlantı elemanları ve türbin disk ve paleti dövme olarak üretilir.",
   soru:"Döküm değil dövme neden uçak iniş takımında tercih edilir?",
   cevap:"İniş takımı çok yüksek darbeli yüklere maruz kalır. Dökümdeki gözenek ve segregasyonlar yorulma dayanımını düşürür. Dövme bu kusurları ortadan kaldırır ve tane akış çizgileri yük doğrultusuna hizalanır."},
  {id:"k82",kategori:"Üretim",ad:"Kaynak yöntemleri",en:"Welding methods",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Havacılıkta en yaygın kaynak yöntemleri: TIG hassas ve temiz kaynak için, MIG otomasyona uygun, elektron ışını kaynağı vakumda yüksek dayanımlı bağlantı, sürtünme karıştırma kaynağı (FSW) alüminyumda ısı oluşturmadan bağlama.",
   soru:"Alüminyumda neden geleneksel kaynak yerine FSW tercih edilebilir?",
   cevap:"Alüminyum 7000 serisi gibi yüksek dayanımlı alaşımlar geleneksel kaynak ısısıyla çökelme sertleşmesini kaybeder. FSW eritme olmadan birleştirir, ısı girdisi çok düşüktür ve mekanik özellikler korunur."},
  {id:"k83",kategori:"Üretim",ad:"Bileşen ömrü ve yenileme",en:"Component life and overhaul",mulakat:true,branslar:["ucak"],
   tanim:"Havacılık parçaları ya zaman/çevrim sınırlıdır (life limited part, LLP) ya da koşul tabanlı olarak değiştirilir. Motor disk gibi LLP ler belirli uçuş saati veya çevrimde zorunlu olarak yenilenir; incelemeye gerek yoktur.",
   soru:"Life limited part neden inceleme yapmadan değiştirilir?",
   cevap:"Bu parçalar yorulma veya sürünme kaynaklı arıza riskini tamamen sıfırlamak için ömürlendirilir. İnceleme bu risk seviyesini garanti edemez. Küçük bir çatlak bile felaket nedeni olabilir."},
  {id:"k84",kategori:"Üretim",ad:"Perçin bağlantısı",en:"Rivet joint",mulakat:true,branslar:["ucak"],
   tanim:"Havacılıkta gövde ve kanat kaplamalarını bağlamak için yaygın kullanılan kalıcı bağlantı yöntemidir. Alüminyum ve titanyum perçinler en yaygın malzemelerdir. Perçin deliği açma işlemi gerilme konsantrasyonu ekler; delik kalitesi yorulma ömrünü doğrudan etkiler.",
   soru:"Yapıştırıcı bağlantı perçin bağlantısına göre ne zaman üstündür?",
   cevap:"Yapıştırıcı yükü geniş alana yayar, gerilme konsantrasyonu yoktur, sızıntı önler ve ağırlık avantajı sağlayabilir. Ancak tamir zordur. Karma tasarımlar her ikisinin avantajlarını bir arada sunar."},
  {id:"k85",kategori:"Üretim",ad:"Yüzey pürüzlülüğü",en:"Surface roughness",mulakat:true,branslar:["ucak","uzay"],
   tanim:"İşlenmiş yüzeyin ideal geometriden sapmasını tanımlayan ölçüdür. Ra ortalama pürüzlülük olup en yaygın parametredir. Pürüzlü yüzeyler yorulma ömrünü düşürür. Türbin kanat yüzeyleri ve kaymalı yüzeyler çok düşük Ra gerektirir.",
   soru:"Parlak yüzey neden her zaman daha iyi değildir?",
   cevap:"Üretim maliyetini yükseltir ve her uygulama bunu gerektirmez. Yapıştırma bağlantılarında yüzeyin biraz pürüzlü olması yapışma alanını artırır. Gerektirilen pürüzlülük seviyesi teknik resimde belirtilmelidir."},
  {id:"k86",kategori:"Üretim",ad:"Prepreg ve otoklav",en:"Prepreg and autoclave",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Prepreg, elyafın önceden belirli oranda reçineyle emprenye edilmiş yarı mamul halidir. Soğuk zincirde saklanır ve ömrü sınırlıdır. Kalıba katman katman serilir ve otoklav denilen basınçlı fırında kürleştirilir.",
   soru:"Prepreg neden soğuk zincirde saklanmak zorundadır?",
   cevap:"Reçine oda sıcaklığında yavaş da olsa kürleşmeye başlar (out-time). Soğukta bu reaksiyon neredeyse durur ve kullanım ömrü uzar. Dondurucularda raf ömrü 12 aya kadar çıkabilirken oda sıcaklığında sadece birkaç hafta ile sınırlıdır."},

  // ── YAPI VE MEKANİK ──────────────────────────────────────────────────
  {id:"k87",kategori:"Yapı ve Mekanik",ad:"Kesme kuvveti ve moment diyagramı",en:"Shear force and bending moment diagram",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Bir kirişe etkiyen yükler altında kesit başına kesme kuvveti ve eğilme momenti değerlerini gösteren diyagramlardır. Moment diyagramının eğimi kesme kuvvetini, kesme kuvveti diyagramının eğimi dağılı yük yoğunluğunu verir. Uçak kanat kirişinde kök kesitte moment maksimum, uç kesitte sıfırdır.",
   soru:"Kanat uçundaki yakıt tüketildikçe kök momenti nasıl değişir?",
   cevap:"Yakıt kanat ucundayken ağırlığı eğilme momentini azaltır. Uç yakıtı tüketilince bu dengeleyici etki kaybolur ve kök momenti artar. Bu yüzden uçaklar uzun yolculukta önce dış tanklardan yakıt harcar."},
  {id:"k88",kategori:"Yapı ve Mekanik",ad:"İnce cidarlı kesit: kutu kirişi",en:"Thin-walled box beam",mulakat:true,branslar:["ucak"],
   tanim:"Kanat ve gövde yapılarındaki iç kuvvetlerin dağılımını inceleyen yapı mekaniği konusudur. Kapalı kesit (kutu kiriş) burulma yükünü çok daha iyi taşır. Uçak kanadının spar ve kaplama sistemi aerodinamik ve yapısal yükleri birlikte taşımak üzere tasarlanmıştır.",
   soru:"Açık ve kapalı ince cidarlı kesit arasındaki fark neden kritiktir?",
   cevap:"Burulma altında açık kesit çok az kayma akışı sürdürebilir ve kesitin bükülmesine neden olur. Kapalı kutu kesit ise kapalı çevre boyunca kayma akışı sürdürür. Kanat kutusunun kapalı kesit olması bu yüzden esastır."},
  {id:"k89",kategori:"Yapı ve Mekanik",ad:"Basınçlı kap tasarımı",en:"Pressure vessel design",mulakat:true,branslar:["ucak","uzay"],
   tanim:"İçinde veya dışında basınç farkı taşıyan kapalı yapılardır. İnce cidarlı silindirde çevresel gerilme σ_θ = pR/t, eksenel gerilme σ_a = pR/2t dir. Çevresel gerilme eksenel gerilmenin iki katıdır. Uçak gövdesi, yakıt tankları ve roket tankları bu formüllerin uygulandığı yapılardır.",
   soru:"Neden gövde boyuna kaynak çevresel kaynaktan kritiktir?",
   cevap:"Çevresel gerilme eksenel gerilmenin iki katı olduğundan boyuna kaynak bu büyük çevresel yükü taşır. Boyuna kaynakların özellikleri daha kritik ve denetimi daha önemlidir."},
  {id:"k90",kategori:"Yapı ve Mekanik",ad:"Hasar toleransı",en:"Damage tolerance",mulakat:true,branslar:["ucak"],
   tanim:"Yapının belirli boyuta kadar çatlak içerse bile güvenli çalışabileceği anlayışına dayanan tasarım felsefesidir. CS-25 kapsamında sivil uçaklarda zorunludur. Kritik çatlak boyutu, muayene aralığı ve kalıntı dayanım analizi üç temel bileşendir.",
   soru:"Neden muayene aralığı kritik çatlak boyutuna göre belirlenir?",
   cevap:"Kritik çatlak boyutuna ulaşmadan çatlağın tespit edilmesi gerekir. Muayene aralığı kritik boyuta ulaşma süresinin yarısına veya daha azına ayarlanır. Böylece bir muayene atlanılsa bile bir sonrakinde çatlak hâlâ kritik boyutun altındadır."},
  {id:"k91",kategori:"Yapı ve Mekanik",ad:"Bileşik kirişlerin analizi",en:"Composite beam analysis",mulakat:false,branslar:["ucak","uzay"],
   tanim:"Farklı malzemelerin kesit boyunca birlikte çalıştığı kirişlerin analizidir. Dönüştürülmüş kesit yöntemiyle modüler oran kullanılarak homojen bir kesit elde edilir. Metal-kompozit hibrit yapılar bu analizle tasarlanır.",
   soru:"Tarafsız eksen her zaman kesitin ortasında mıdır?",
   cevap:"Hayır. Homojen simetrik kesitte ortadadır. Farklı malzeme veya asimetrik geometride tarafsız eksen rijitlik merkezine göre kayar. Yanlış tarafsız eksen kabulü moment hesabında büyük hataya yol açar."},
  {id:"k92",kategori:"Yapı ve Mekanik",ad:"Titreşim modları",en:"Vibration modes",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Yapının doğal titreşim şekilleridir. Her mod farklı bir doğal frekansa ve şekle sahiptir. FEA modal analizi bu frekans ve şekilleri hesaplar. Motor zorlama frekansları kanat doğal frekanslarından uzak tutulmalıdır.",
   soru:"Modal analiz neden rüzgâr tünelinden önce yapılır?",
   cevap:"Flutter riski değerlendirilir. Belirli bir aerodinamik hızda aerodinamik kuvvetler bir yapı modunu uyarabiliyorsa flutter gerçekleşir. Tasarım aşamasında modları tehlikeli bölgeden çıkarmak en az maliyetli yoldur."},
  {id:"k93",kategori:"Yapı ve Mekanik",ad:"Kontrol yüzeyi kütle dengesi",en:"Mass balance",mulakat:true,branslar:["ucak"],
   tanim:"Kontrol yüzeylerinin menteşe etrafındaki ağırlık dengesini sağlamak için yapılan düzenlemedir. Menteşe arkasındaki kontrol yüzeyi öne doğru ağır olursa salınıma girebilir (flutter). Kütle dengesi menteşe önüne ağırlık ekleyerek bu momenti azaltır.",
   soru:"Kontrol yüzeyi neden fabrikada statik balans için tartılır?",
   cevap:"Üretim toleransları yüzey ağırlığını etkileyebilir. Statik balans belirtilen ağırlık merkezi pozisyonunu doğrular. Dışı olan yüzey flutter sınırını düşürür. Bu yüzden her yüzey değişimi sonrası balans tekrar kontrol edilir."},
  {id:"k94",kategori:"Yapı ve Mekanik",ad:"Sandviç yapı",en:"Sandwich structure",mulakat:true,branslar:["ucak","uzay"],
   tanim:"İki ince yüzey tabakası arasında hafif bir çekirdek malzemeden oluşan yapıdır. Eğilme rijitliği çok yüksek, ağırlık çok düşüktür. İki yüzey tabakası eğilme momentini, çekirdek ise kesme kuvvetini taşır. Uçak radome, kabin iç panelleri ve zemin tahtaları bu yapıdan üretilir.",
   soru:"Sandviç yapının zayıf noktası nedir?",
   cevap:"Yüzey tabakası ile çekirdek arasındaki yapışma ayrılması darbe veya nem girişiyle başlayabilir. Kenar bağlantılarında yükün nasıl aktarıldığı özenle tasarlanmalıdır. Onarım geleneksel metal yapıya göre daha karmaşıktır."},
  {id:"k95",kategori:"Yapı ve Mekanik",ad:"V-n diyagramı",en:"V-n diagram",mulakat:true,branslar:["ucak"],
   tanim:"Uçağın alabileceği azami ve asgari yük faktörünü hıza bağlı olarak gösteren uçuş zarfı diyagramıdır. Yapısal sınır yük ve nihai yük bu diyagramdan okunur. Türbülans çizgisi de diyagrama eklenir ve en kısıtlayıcı durum belirlenir.",
   soru:"Tasarım manevrası hızında neden tam kumanda hareketi güvenlidir?",
   cevap:"Va da veya altındaki hızda tam kumanda hareketi stall dan önce maksimum yük faktörüne ulaşamaz. Va nın üstünde ise yapısal sınırı aşan yük faktörü oluşturabilir. Bu yüzden türbülans sırasında Va nın altında uçmak tavsiye edilir."},
  {id:"k96",kategori:"Yapı ve Mekanik",ad:"Kalıntı gerilme",en:"Residual stress",mulakat:true,branslar:["ucak","uzay"],
   tanim:"Dış yük kaldırıldıktan sonra malzeme veya yapı içinde kalan iç gerilmedir. Basma kalıntı gerilmesi yorulma çatlağı başlangıcını geciktirir; bu yüzden shot peening ve cold working bilinçli olarak uygulanır. Çekme kalıntı gerilmesi ise yorulma ömrünü kısaltır.",
   soru:"Kaynak sonrası neden gerilme giderme tavlaması yapılır?",
   cevap:"Kaynak sırasında lokal ısıtma ve hızlı soğuma büyük iç gerilmeler bırakır. Bu gerilmeler çatlak başlangıcını hızlandırabilir ve gerilme korozyon çatlamasını tetikleyebilir. Gerilme giderme tavlaması bu gerilmeleri azaltır."}
];
